### ISSUE TITLE
Using a private registry

### ISSUE THREAD

**Issue by starfoxx82** [konstruktoid/ansible-docker-rootless#3]
Hi, 
firstly thank for this good job. Do you plan to use an private registry with authentication to pull your images? Or do you see a way to do this?

thx

**Comment by konstruktoid** [comment]
Hi @starfoxx82, do you mean adding support for private repositories in the Ansible role?

**Comment by starfoxx82** [comment]
hi @konstruktoid, that is what i mean  :-)
I think that's cool. What do you think about that?

**Comment by konstruktoid** [comment]
Doesn't setting the private repository as usual work?

```yaml
  docker_container:
    name: container
    image: <private_repository>/<container_image>
  ```

**Comment by starfoxx82** [comment]
that works, but when you have an registry with credentials. How will it work?

**Comment by konstruktoid** [comment]
See the examples at https://docs.ansible.com/ansible/latest/collections/community/general/docker_login_module.html, e.g.

```
- name: Log into private registry and force re-authorization
  become: 'yes'
  become_user: "{{ docker_user }}"
  community.general.docker_login:
    registry_url: your.private.registry.io
    username: yourself
    password: secrets3
    reauthorize: yes
```
